---
driver:
  name: vagrant
  network:
    - ["private_network", { ip: "192.168.55.55"}]

verifier:
  name: inspec
  sudo: true
  patterns:
    - tests/integration/default
    
provisioner:
  name: salt_solo
  omnibus_cachier: true
  formula: spark
  pillars-from-files:
    spark.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - spark
  grains:
    roles:
      - spark-worker

  state_top:
    base:
      "*":
        - spark
        - spark.debug

platforms:
  - name: ubuntu
    driver:
      box: bento/ubuntu-17.04

suites:
  - name: default

  - name: worker
    verifier:
      patterns:
        - tests/integration/default/
    provisioner:
      state_top:
        base:
          '*':
            - spark
            - spark.debug
            - spark.worker
      
  - name: master
    verifier:
      patterns:
        - tests/integration/default/
    provisioner:
      state_top:
        base:
          '*':
            - spark
            - spark.debug
            - spark.master
