---
driver:
  name: vagrant
  network:
    - ["private_network", { ip: "192.168.55.55"}]

verifier:
  name: inspec
  sudo: true
  patterns:
    - tests/integration/default
    
provisioner:
  name: salt_solo
  log_level: debug
  omnibus_cachier: true
  salt_install: bootstrap
  salt_version: latest
  salt_minion_id: kitchen-test-spark
  
  formula: spark
  pillars-from-files:
    spark.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - spark
  state_top:
    base:
      "*":
        - spark
        - spark.debug

platforms:
  - name: ubuntu
    driver:
      box: bento/ubuntu-17.04

suites:
  - name: default

  - name: worker
    verifier:
      patterns:
        - tests/integration/default/
        
    provisioner:
      grains:
        roles:
          - spark-worker

      state_top:
        base:
          '*':
            - spark
            - spark.debug
            - spark.worker
      
  - name: master
    verifier:
      patterns:
        - tests/integration/default/
    provisioner:
      grains:
        roles:
          - spark-master
      state_top:
        base:
          '*':
            - spark
            - spark.debug
            - spark.master
