---
driver:
  name: docker
  privileged: true
  
verifier:
  name: inspec
  sudo: true
        
provisioner:
  name: salt_solo
  log_level: debug
  omnibus_cachier: true
  salt_install: bootstrap
  salt_version: latest
  salt_minion_id: kitchen-test-spark
  
  formula: spark
  pillars-from-files:
    spark.sls: pillar.example
  pillars:
    top.sls:
      base:
        "*":
          - spark
  state_top:
    base:
      "*":
        - spark
        - spark.debug

platforms:
  - name: ubuntu-17.04

suites:
  - name: default
    verifier:
      inspec_tests:
        - name: spark-default
          path: test/integration/default
      controls:
        - spark-baseline
