sudo: required
services:
  - docker

before_install:
  - sudo apt-get update
  - curl -L http://bootstrap.saltstack.org | sudo sh -s -- git develop

install:
  - pip install PyYAML
  - pip install virtualenv
  - |
    cat <<EOF | tee  Gemfile
    source 'https://rubygems.org'
    gem 'rake'
    gem 'test-kitchen'
    gem 'kitchen-docker'
    gem 'kitchen-inspec'
    gem 'inspec'
    gem 'kitchen-salt', :git => 'https://github.com/salt-formulas/kitchen-salt.git'
  - bundle install

before_script:
  - set -o pipefail
  - make test | tail

script:
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml bundle exec kitchen test 
